name: Bug report
description: Create a report to help us improve Amplify UI Android

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report! Try to include as much information as you can.

  - type: checkboxes
    attributes:
      label: |
        Before creating a new issue, please confirm:
      options:
        - label: I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui-android/issues?q=is%3Aissue+).
          required: true
        - label: I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui-android/blob/main/CONTRIBUTING.md#reporting-bugsfeature-requests).
          required: true

  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: dropdown
    attributes:
      label: Which UI component?
      description: Select one of our UI components below.
      multiple: true
      options:
        - Authenticator
        - Liveness
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Gradle script dependencies
      description: |
        Please provide the version of Amplify UI Android being used from your `build.gradle (Module: app)` file.
      value: |
        ```groovy
        // Put output below this line

        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment information
      description: |
        Please run the following command inside your project and copy/paste the output below:
        ```
          ./gradlew --version
        ```
      value: |
        ```
        # Put output below this line


        ```
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Details
  - type: input
    attributes:
      label: Please include any relevant guides or documentation you're referencing
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps (if applicable)
      description: |
        How do you trigger this bug? Please walk us through it step by step. Screenshots can be attached in textarea below.
      placeholder: |
        1. Install '...'
        2. Configure '...'
        3. Go to '...'
        4. See error
  - type: textarea
    attributes:
      label: Code Snippet
      description: |
        Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. 

        **Be sure to remove any sensitive data.**
      value: |
        ```java
        // Put your code below this line.

        ```
  - type: textarea
    attributes:
      label: Log output
      description: |
        For example, error messages or stack traces.

        **Be sure to remove any sensitive data.**
      value: |
        ```
        // Put your logs below this line


        ```
  - type: markdown
    attributes:
      value: |
        ## Configuration
  - type: textarea
    attributes:
      label: amplifyconfiguration.json
      description: If applicable, please provide your `amplifyconfiguration.json` file with sensitive information removed.
      placeholder: |
        ```json
          {
            "UserAgent": "aws-amplify-cli/2.0",
            "Version": "1.0",
            "api": {
                "plugins": {
                    "awsAPIPlugin": {
                        "amplifyDatasource": {
                            "endpointType": "GraphQL",
                            "endpoint": "https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-2.amazonaws.com/graphql",
                            "region": "us-east-2",
                            "authorizationType": "API_KEY",
                            "apiKey": "xxx-xxxxxxxxxxxxxxxxxxxxxxxxxx"
                        }
                    }
                }
            }
        }
        ```
  - type: textarea
    attributes:
      label: Additional information and screenshots
      description: |
        If you have any additional information, workarounds, etc. for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
