default_platform(:android)

import_from_git(
    url: 'https://github.com/aws-amplify/amplify-ci-support',
    branch: 'android/fastlane-actions',
    path: './src/fastlane/release_actions/fastlane/AndroidAppsFastfile'
)

# When testing against local changes, comment out the above and use the line below instead.
# import '~/github/aws-amplify/amplify-ci-support/src/fastlane/release_actions/fastlane/AndroidAppsFastfile'

platform :android do |options|
  override_lane :build_parameters do
    project_root = File.expand_path("#{Dir.pwd()}/../..")
    UI.message("Building version groups for amplify-ui-android from #{project_root}")
    {
      repo: 'aws-amplify/amplify-ui-android',
      product_name: 'Amplify UI Liveness Android',
      releases: [
        {
          release_tag_prefix: 'release_liveness_v',
          gradle_properties_path: "#{project_root}/liveness/gradle.properties",
          doc_files_to_update: [],
          release_title: 'Amplify UI Liveness Android',
          changelog_path: "#{project_root}/liveness/CHANGELOG.md",
          component_name: "Liveness",
          top_level_docs_to_update: ["#{project_root}/README.md"],
          sample_build_files_to_update: ["#{project_root}/samples/liveness/build.gradle"],
          changelog_include_scopes: ["liveness", "Liveness", "all"],
          changelog_ignore_scopes: ["authenticator", "Authenticator"]
        },
        {
          release_tag_prefix: 'release_authenticator_v',
          gradle_properties_path: "#{project_root}/authenticator/gradle.properties",
          doc_files_to_update: ["#{project_root}/authenticator/README.md"],
          release_title: 'Amplify UI Authenticator Android',
          changelog_path: "#{project_root}/authenticator/CHANGELOG.md",
          component_name: "Authenticator",
          top_level_docs_to_update: ["#{project_root}/README.md"],
          sample_build_files_to_update: ["#{project_root}/samples/authenticator/build.gradle"],
          changelog_include_scopes: [],
          changelog_ignore_scopes: ["liveness", "Liveness"]
        }
      ]
    }
  end
end
