name: Unit tests
run-name: Unit tests for ${{ github.ref }}

on:
  pull_request:
    branches:
      - 'main'
  merge_group:
    types: [checks_requested]

env:
  AWS_REGION: "us-east-1"

jobs:
  ci-unit-tests:
    permissions:
      id-token: write # This is required for requesting the JWT with configure-aws-credentials
      contents: read # This is required for actions/checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2
        with:
          role-to-assume: ${{ vars.AMPLIFY_UI_ANDROID_CI_TESTS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Run Unit Tests
        uses: aws-actions/aws-codebuild-run-build@f202c327329cbbebd13f986f74af162a8539b5fd # v1
        with:
          project-name: Amplify-UI-Android-Build
