name: Notify Comments on Open Issues

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ !github.event.issue.pull_request && (github.event.issue.state == 'closed' || contains(github.event.issue.labels.*.name, 'pending-response') || contains(github.event.issue.labels.*.name, 'closing soon')) }}
    steps:
      - name: Run webhook curl command
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_COMMENT_WEBHOOK_URL }}
          BODY: ${{ toJson(github.event.comment.body) }}
          COMMENT_URL: ${{github.event.comment.html_url}} d
        shell: bash
        run: echo $BODY | xargs -I {} curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json" --data '{"body":"{}", "issue":"'$COMMENT_URL'"}'
